package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", schema = "sfe")
public class Empresa implements java.io.Serializable {

	private int empId;
	private String empDescripcion;
	private String empNick;
	private String empTelefono;
	private String empDireccion;
	private String empEmail;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModificacion;
	private String empNit;
	private String empCitec;
	private int muniId;
	private int tidId;
	private int empRegimen;



	public Empresa(int empId, String empDescripcion, String empNick, String empTelefono, String empDireccion,
			String empEmail, int uepId, Date fechaCreacion, String empNit, String empCitec , int muniId, int tidId, int empRegimen) {
		this.empId = empId;
		this.empDescripcion = empDescripcion;
		this.empNick = empNick;
		this.empTelefono = empTelefono;
		this.empDireccion = empDireccion;
		this.empEmail = empEmail;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.empNit = empNit;
		this.empCitec = empCitec;
		this.muniId = muniId;
		this.tidId = tidId;
		}

	public Empresa(int empId, String empDescripcion, String empNick, String empTelefono, String empDireccion,
			String empEmail, int uepId, Date fechaCreacion, Integer userModifica, Date fechaModificacion, String empNit,
			String empCitec , int muniId, int tidId , int empRegimen) {
		this.empId = empId;
		this.empDescripcion = empDescripcion;
		this.empNick = empNick;
		this.empTelefono = empTelefono;
		this.empDireccion = empDireccion;
		this.empEmail = empEmail;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModificacion = fechaModificacion;
		this.empNit = empNit;
		this.empCitec = empCitec;
		this.muniId = muniId;
		this.tidId = tidId;
	}

	@Id

	@Column(name = "emp_id", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "emp_descripcion", nullable = false, length = 250)
	public String getEmpDescripcion() {
		return this.empDescripcion;
	}

	public void setEmpDescripcion(String empDescripcion) {
		this.empDescripcion = empDescripcion;
	}

	@Column(name = "emp_nick", nullable = false, length = 250)
	public String getEmpNick() {
		return this.empNick;
	}

	public void setEmpNick(String empNick) {
		this.empNick = empNick;
	}

	@Column(name = "emp_telefono", nullable = false, length = 20)
	public String getEmpTelefono() {
		return this.empTelefono;
	}

	public void setEmpTelefono(String empTelefono) {
		this.empTelefono = empTelefono;
	}

	@Column(name = "emp_direccion", nullable = false, length = 250)
	public String getEmpDireccion() {
		return this.empDireccion;
	}

	public void setEmpDireccion(String empDireccion) {
		this.empDireccion = empDireccion;
	}

	@Column(name = "emp_email", nullable = false, length = 250)
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "emp_nit", nullable = false, length = 20)
	public String getEmpNit() {
		return this.empNit;
	}

	public void setEmpNit(String empNit) {
		this.empNit = empNit;
	}

	@Column(name = "emp_citec", length = 50)
	public String getEmpCitec() {
		return this.empCitec;
	}

	public void setEmpCitec(String empCitec) {
		this.empCitec = empCitec;
	}
	
	@Column(name = "muni_id")
	public int getMuniId() {
		return muniId;
	}

	public void setMuniId(int muniId) {
		this.muniId = muniId;
	}

	@Column(name = "tid_id")
	public int getTidId() {
		return tidId;
	}

	public void setTidId(int tidId) {
		this.tidId = tidId;
	}

	@Column(name = "emp_regimen")
	public int getempRegimen() {
		return empRegimen;
	}

	public void setempRegimen(int empRegimen) {
		this.empRegimen = empRegimen;
	}
	
	public Empresa() {
	}


}
