package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", schema = "sfe")
public class Factura implements java.io.Serializable {

	
	private int facId;
	private String facNumFactura;
	private Date facFechaFactura;
	private Date facFecaPago;
	private int cliId;
	private int refId;
	private int uepId;
	private double facSubTotal;
	private double facTotal;
	private double facIva;
	private Double facImpConsumo;
	private Date fechaCreacion;
	private String facTipo;
	private String facObservacion;
	private String facNotaNumero;
	private String facPath;
	private String facNumOriginal;

	


	

	

	

	public Factura(int facId, String facNumFactura, Date facFechaFactura, Date facFecaPago, int cliId, int refId,
			int uepId, double facSubTotal, double facTotal, double facIva, Date fechaCreacion) {
		this.facId = facId;
		this.facNumFactura = facNumFactura;
		this.facFechaFactura = facFechaFactura;
		this.facFecaPago = facFecaPago;
		this.cliId = cliId;
		this.refId = refId;
		this.uepId = uepId;
		this.facSubTotal = facSubTotal;
		this.facTotal = facTotal;
		this.facIva = facIva;
		this.fechaCreacion = fechaCreacion;
	}

	public Factura(int facId, String facNumFactura, Date facFechaFactura, Date facFecaPago, int cliId, int refId,
			int uepId, double facSubTotal, double facTotal, double facIva, Double facImpConsumo, Date fechaCreacion) {
		this.facId = facId;
		this.facNumFactura = facNumFactura;
		this.facFechaFactura = facFechaFactura;
		this.facFecaPago = facFecaPago;
		this.cliId = cliId;
		this.refId = refId;
		this.uepId = uepId;
		this.facSubTotal = facSubTotal;
		this.facTotal = facTotal;
		this.facIva = facIva;
		this.facImpConsumo = facImpConsumo;
		this.fechaCreacion = fechaCreacion;
	}

	@Id
	@SequenceGenerator(name="FACTURA_GENERATOR", sequenceName="SEQ_FACTURA" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="FACTURA_GENERATOR" )
	@Column(name = "fac_id", unique = true, nullable = false)
	public int getFacId() {
		return this.facId;
	}

	public void setFacId(int facId) {
		this.facId = facId;
	}
	@Column(name = "fac_num_original", nullable = false, length = 20)
	public String getFacNumOriginal() {
		return facNumOriginal;
	}

	public void setFacNumOriginal(String facNumOriginal) {
		this.facNumOriginal = facNumOriginal;
	}

	public Factura() {
	}

	@Column(name = "fac_num_factura", nullable = false, length = 20)
	public String getFacNumFactura() {
		return this.facNumFactura;
	}

	public void setFacNumFactura(String facNumFactura) {
		this.facNumFactura = facNumFactura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fac_fecha_factura", nullable = false, length = 27)
	public Date getFacFechaFactura() {
		return this.facFechaFactura;
	}

	public void setFacFechaFactura(Date facFechaFactura) {
		this.facFechaFactura = facFechaFactura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fac_feca_pago", nullable = false, length = 13)
	public Date getFacFecaPago() {
		return this.facFecaPago;
	}

	public void setFacFecaPago(Date facFecaPago) {
		this.facFecaPago = facFecaPago;
	}

	@Column(name = "cli_id", nullable = false)
	public int getCliId() {
		return this.cliId;
	}

	public void setCliId(int cliId) {
		this.cliId = cliId;
	}

	@Column(name = "ref_id", nullable = false)
	public int getRefId() {
		return this.refId;
	}

	public void setRefId(int refId) {
		this.refId = refId;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Column(name = "fac_sub_total", nullable = false, precision = 17, scale = 17)
	public double getFacSubTotal() {
		return this.facSubTotal;
	}

	public void setFacSubTotal(double facSubTotal) {
		this.facSubTotal = facSubTotal;
	}

	@Column(name = "fac_total", nullable = false, precision = 17, scale = 17)
	public double getFacTotal() {
		return this.facTotal;
	}

	public void setFacTotal(double facTotal) {
		this.facTotal = facTotal;
	}

	@Column(name = "fac_iva", nullable = false, precision = 17, scale = 17)
	public double getFacIva() {
		return this.facIva;
	}

	public void setFacIva(double facIva) {
		this.facIva = facIva;
	}

	@Column(name = "fac_imp_consumo", precision = 17, scale = 17)
	public Double getFacImpConsumo() {
		return this.facImpConsumo;
	}

	public void setFacImpConsumo(Double facImpConsumo) {
		this.facImpConsumo = facImpConsumo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}
	
	@Column(name = "fac_tipo", nullable = false, length = 20)
	public String getFacTipo() {
		return facTipo;
	}

	public void setFacTipo(String facTipo) {
		this.facTipo = facTipo;
	}
	
	@Column(name = "fac_observacion", nullable = false, length = 2000)
	public String getFacObservacion() {
		return facObservacion;
	}

	public void setFacObservacion(String facObservacion) {
		this.facObservacion = facObservacion;
	}
	
	@Column(name = "fac_nota_numero", nullable = false, length = 50)
	public String getFacNotaNumero() {
		return facNotaNumero;
	}

	public void setFacNotaNumero(String facNotaNumero) {
		this.facNotaNumero = facNotaNumero;
	}
	
	@Column(name = "fac_path", nullable = false, length = 100)
	public String getFacPath() {
		return facPath;
	}

	public void setFacPath(String facPath) {
		this.facPath = facPath;
	}

}
