package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FacturaDetalle generated by hbm2java
 */
@Entity
@Table(name = "factura_detalle", schema = "sfe")
public class FacturaDetalle implements java.io.Serializable {

	private int fadId;
	private double fadCantidad;
	private Integer proId;
	private int pvmId;
	private int facId;
	private Double fadDescuento;
	private Double fadSubtotal;
	private Double fadValorUnitario;
	private String fadObservacion;

	
	public FacturaDetalle() {
	}

	public FacturaDetalle(int fadId, int fadCantidad, int pvmId, int facId) {
		this.fadId = fadId;
		this.fadCantidad = fadCantidad;
		this.pvmId = pvmId;
		this.facId = facId;
	}

	public FacturaDetalle(int fadId, int fadCantidad, Integer proId, int pvmId, int facId, Double fadDescuento,
			Double fadSubtotal, Double fadValorUnitario) {
		this.fadId = fadId;
		this.fadCantidad = fadCantidad;
		this.proId = proId;
		this.pvmId = pvmId;
		this.facId = facId;
		this.fadDescuento = fadDescuento;
		this.fadSubtotal = fadSubtotal;
	}

	@Id
	@SequenceGenerator(name="FACTURA_DETALLE_GENERATOR", sequenceName="SEQ_FACTURA_DETALLE" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="FACTURA_DETALLE_GENERATOR")
	@Column(name = "fad_id", unique = true, nullable = false)
	public int getFadId() {
		return this.fadId;
	}

	public void setFadId(int fadId) {
		this.fadId = fadId;
	}

	@Column(name = "fad_cantidad", nullable = false)
	public double getFadCantidad() {
		return this.fadCantidad;
	}

	public void setFadCantidad(double d) {
		this.fadCantidad = d;
	}

	@Column(name = "pro_id")
	public Integer getProId() {
		return this.proId;
	}

	public void setProId(Integer proId) {
		this.proId = proId;
	}

	@Column(name = "pvm_id", nullable = false)
	public int getPvmId() {
		return this.pvmId;
	}

	public void setPvmId(int pvmId) {
		this.pvmId = pvmId;
	}

	@Column(name = "fac_id", nullable = false)
	public int getFacId() {
		return this.facId;
	}

	public void setFacId(int facId) {
		this.facId = facId;
	}

	@Column(name = "fad_descuento", precision = 17, scale = 17)
	public Double getFadDescuento() {
		return this.fadDescuento;
	}

	public void setFadDescuento(Double fadDescuento) {
		this.fadDescuento = fadDescuento;
	}

	@Column(name = "fad_subtotal", precision = 17, scale = 17)
	public Double getFadSubtotal() {
		return this.fadSubtotal;
	}

	public void setFadSubtotal(Double fadSubtotal) {
		this.fadSubtotal = fadSubtotal;
	}
	
	@Column(name = "fad_valor_unitario", precision = 17, scale = 17)
	public Double getFadValorUnitario() {
		return fadValorUnitario;
	}

	public void setFadValorUnitario(Double fadValorUnitario) {
		this.fadValorUnitario = fadValorUnitario;
	}
	
	@Column(name = "fad_observacion", nullable = false, length = 2000)
	public String getFadObservacion() {
		return fadObservacion;
	}

	public void setFadObservacion(String fadObservacion) {
		this.fadObservacion = fadObservacion;
	}


}
