package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "group", schema = "sfe")
public class Group implements java.io.Serializable {

	private int gruId;
	private int usuId;
	private String gruDescripcion;

	public Group() {
	}

	public Group(int gruId, int usuId, String gruDescripcion) {
		this.gruId = gruId;
		this.usuId = usuId;
		this.gruDescripcion = gruDescripcion;
	}

	@Id

	@Column(name = "gru_id", unique = true, nullable = false)
	public int getGruId() {
		return this.gruId;
	}

	public void setGruId(int gruId) {
		this.gruId = gruId;
	}

	@Column(name = "usu_id", nullable = false)
	public int getUsuId() {
		return this.usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	@Column(name = "gru_descripcion", nullable = false, length = 20)
	public String getGruDescripcion() {
		return this.gruDescripcion;
	}

	public void setGruDescripcion(String gruDescripcion) {
		this.gruDescripcion = gruDescripcion;
	}

}
