package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", schema = "sfe")
public class Marca implements java.io.Serializable {

	private int marId;
	private String marDescripcion;
	private char marEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Marca() {
	}

	public Marca(int marId, String marDescripcion, char marEstado, int uepId, Date fechaCreacion) {
		this.marId = marId;
		this.marDescripcion = marDescripcion;
		this.marEstado = marEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public Marca(int marId, String marDescripcion, char marEstado, int uepId, Date fechaCreacion, Integer userModifica,
			Date fechaModifica, Set<Producto> productos) {
		this.marId = marId;
		this.marDescripcion = marDescripcion;
		this.marEstado = marEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
		this.productos = productos;
	}

	@Id
	@SequenceGenerator(name= "MARCA_GENERATOR", sequenceName= "SEQ_MARCA" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator= "MARCA_GENERATOR" )
	@Column(name = "mar_id", unique = true, nullable = false)
	public int getMarId() {
		return this.marId;
	}

	public void setMarId(int marId) {
		this.marId = marId;
	}

	@Column(name = "mar_descripcion", nullable = false, length = 250)
	public String getMarDescripcion() {
		return this.marDescripcion;
	}

	public void setMarDescripcion(String marDescripcion) {
		this.marDescripcion = marDescripcion;
	}

	@Column(name = "mar_estado", nullable = false, length = 1)
	public char getMarEstado() {
		return this.marEstado;
	}

	public void setMarEstado(char marEstado) {
		this.marEstado = marEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
