package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio", schema = "sfe")
public class Municipio implements java.io.Serializable {

	private int muniId;
	private String muniDescripcion;
	private String muniCodigo;
	private int depId;
	private char muniEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModfica;
	private Date fechaModifica;

	public Municipio() {
	}

	public Municipio(int muniId, String muniDescripcion, String muniCodigo, int depId, char muniEstado, int uepId,
			Date fechaCreacion) {
		this.muniId = muniId;
		this.muniDescripcion = muniDescripcion;
		this.muniCodigo = muniCodigo;
		this.depId = depId;
		this.muniEstado = muniEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public Municipio(int muniId, String muniDescripcion, String muniCodigo, int depId, char muniEstado, int uepId,
			Date fechaCreacion, Integer userModfica, Date fechaModifica) {
		this.muniId = muniId;
		this.muniDescripcion = muniDescripcion;
		this.muniCodigo = muniCodigo;
		this.depId = depId;
		this.muniEstado = muniEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModfica = userModfica;
		this.fechaModifica = fechaModifica;
	}

	@Id

	@Column(name = "muni_id", unique = true, nullable = false)
	public int getMuniId() {
		return this.muniId;
	}

	public void setMuniId(int muniId) {
		this.muniId = muniId;
	}

	@Column(name = "muni_descripcion", nullable = false, length = 250)
	public String getMuniDescripcion() {
		return this.muniDescripcion;
	}

	public void setMuniDescripcion(String muniDescripcion) {
		this.muniDescripcion = muniDescripcion;
	}

	@Column(name = "muni_codigo", nullable = false, length = 5)
	public String getMuniCodigo() {
		return this.muniCodigo;
	}

	public void setMuniCodigo(String muniCodigo) {
		this.muniCodigo = muniCodigo;
	}

	@Column(name = "dep_id", nullable = false)
	public int getDepId() {
		return this.depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}

	@Column(name = "muni_estado", nullable = false, length = 1)
	public char getMuniEstado() {
		return this.muniEstado;
	}

	public void setMuniEstado(char muniEstado) {
		this.muniEstado = muniEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modfica")
	public Integer getUserModfica() {
		return this.userModfica;
	}

	public void setUserModfica(Integer userModfica) {
		this.userModfica = userModfica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
