package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "sfe")
public class Perfil implements java.io.Serializable {

	private int perId;
	private String perDescripcion;
	private char perEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;

	public Perfil() {
	}

	public Perfil(int perId, String perDescripcion, char perEstado, int uepId, Date fechaCreacion) {
		this.perId = perId;
		this.perDescripcion = perDescripcion;
		this.perEstado = perEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public Perfil(int perId, String perDescripcion, char perEstado, int uepId, Date fechaCreacion, Integer userModifica,
			Date fechaModifica) {
		this.perId = perId;
		this.perDescripcion = perDescripcion;
		this.perEstado = perEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
	}

	@Id

	@Column(name = "per_id", unique = true, nullable = false)
	public int getPerId() {
		return this.perId;
	}

	public void setPerId(int perId) {
		this.perId = perId;
	}

	@Column(name = "per_descripcion", nullable = false, length = 250)
	public String getPerDescripcion() {
		return this.perDescripcion;
	}

	public void setPerDescripcion(String perDescripcion) {
		this.perDescripcion = perDescripcion;
	}

	@Column(name = "per_estado", nullable = false, length = 1)
	public char getPerEstado() {
		return this.perEstado;
	}

	public void setPerEstado(char perEstado) {
		this.perEstado = perEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
