package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "sfe", uniqueConstraints = @UniqueConstraint(columnNames = "pro_referencia"))
public class Producto implements java.io.Serializable {

	private int proId;
	private Marca marca;
	private TipoProducto tipoProducto;
	private String proDescripcion;
	private String proReferencia;
	private char proEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;
	private Set<ProductoValorMedida> productoValorMedidas = new HashSet<ProductoValorMedida>(0);

	public Producto() {
	}

	public Producto(int proId, Marca marca, TipoProducto tipoProducto, String proDescripcion, String proReferencia,
			char proEstado, int uepId, Date fechaCreacion) {
		this.proId = proId;
		this.marca = marca;
		this.tipoProducto = tipoProducto;
		this.proDescripcion = proDescripcion;
		this.proReferencia = proReferencia;
		this.proEstado = proEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public Producto(int proId, Marca marca, TipoProducto tipoProducto, String proDescripcion, String proReferencia,
			char proEstado, int uepId, Date fechaCreacion, Integer userModifica, Date fechaModifica,
			Set<ProductoValorMedida> productoValorMedidas) {
		this.proId = proId;
		this.marca = marca;
		this.tipoProducto = tipoProducto;
		this.proDescripcion = proDescripcion;
		this.proReferencia = proReferencia;
		this.proEstado = proEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
		this.productoValorMedidas = productoValorMedidas;
	}

	@Id
	@SequenceGenerator(name="PRODUCTO_GENERATOR", sequenceName="SEQ_PRODUCTO" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PRODUCTO_GENERATOR" )
	@Column(name = "pro_id", unique = true, nullable = false)
	public int getProId() {
		return this.proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "mar_id", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tip_id", nullable = false)
	public TipoProducto getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(TipoProducto tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	@Column(name = "pro_descripcion", nullable = false, length = 250)
	public String getProDescripcion() {
		return this.proDescripcion;
	}

	public void setProDescripcion(String proDescripcion) {
		this.proDescripcion = proDescripcion;
	}

	@Column(name = "pro_referencia", unique = true, nullable = false, length = 50)
	public String getProReferencia() {
		return this.proReferencia;
	}

	public void setProReferencia(String proReferencia) {
		this.proReferencia = proReferencia;
	}

	@Column(name = "pro_estado", nullable = false, length = 1)
	public char getProEstado() {
		return this.proEstado;
	}

	public void setProEstado(char proEstado) {
		this.proEstado = proEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<ProductoValorMedida> getProductoValorMedidas() {
		return this.productoValorMedidas;
	}

	public void setProductoValorMedidas(Set<ProductoValorMedida> productoValorMedidas) {
		this.productoValorMedidas = productoValorMedidas;
	}

}
