package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoValorMedida generated by hbm2java
 */
@Entity
@Table(name = "producto_valor_medida", schema = "sfe")
public class ProductoValorMedida implements java.io.Serializable {

	private int pvmId;
	private Producto producto;
	private UnidadMedida unidadMedida;
	private double pvmValor;
	private double pvmCantidad;
	private int tpcId;
	private char pvmEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;

	public ProductoValorMedida() {
	}

	public ProductoValorMedida(int pvmId, Producto producto, UnidadMedida unidadMedida, double pvmValor, int tpcId,
			char pvmEstado, int uepId, Date fechaCreacion) {
		this.pvmId = pvmId;
		this.producto = producto;
		this.unidadMedida = unidadMedida;
		this.pvmValor = pvmValor;
		this.tpcId = tpcId;
		this.pvmEstado = pvmEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public ProductoValorMedida(int pvmId, Producto producto, UnidadMedida unidadMedida, double pvmValor, int tpcId,
			char pvmEstado, int uepId, Date fechaCreacion, Integer userModifica, Date fechaModifica) {
		this.pvmId = pvmId;
		this.producto = producto;
		this.unidadMedida = unidadMedida;
		this.pvmValor = pvmValor;
		this.tpcId = tpcId;
		this.pvmEstado = pvmEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
	}

	@Id
	@SequenceGenerator(name="PVM_GENERATOR", sequenceName="SEQ_PRODUCTO_VALOR_MEDIDA" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PVM_GENERATOR" )
	@Column(name = "pvm_id", unique = true, nullable = false)
	public int getPvmId() {
		return this.pvmId;
	}

	public void setPvmId(int pvmId) {
		this.pvmId = pvmId;
	}
	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pro_id", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unm_id", nullable = false)
	public UnidadMedida getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UnidadMedida unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	@Column(name = "pvm_valor", nullable = false, precision = 17, scale = 17)
	public double getPvmValor() {
		return this.pvmValor;
	}

	public void setPvmValor(double pvmValor) {
		this.pvmValor = pvmValor;
	}
	
	@Column(name = "pvm_cantidad", nullable = false, precision = 17, scale = 17)
	public double getPvmCantidad() {
		return pvmCantidad;
	}

	public void setPvmCantidad(double pvmCantidad) {
		this.pvmCantidad = pvmCantidad;
	}

	@Column(name = "tpc_id", nullable = false)
	public int getTpcId() {
		return this.tpcId;
	}

	public void setTpcId(int tpcId) {
		this.tpcId = tpcId;
	}

	@Column(name = "pvm_estado", nullable = false, length = 1)
	public char getPvmEstado() {
		return this.pvmEstado;
	}

	public void setPvmEstado(char pvmEstado) {
		this.pvmEstado = pvmEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
