package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoProducto generated by hbm2java
 */
@Entity
@Table(name = "tipo_producto", schema = "sfe")
@NamedQuery(name="TipoProducto.findAll", query="SELECT p FROM TipoProducto p")
public class TipoProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tipId;
	private String tipDescripcion;
	private char tipEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public TipoProducto() {
	}

	public TipoProducto(int tipId, String tipDescripcion, char tipEstado, int uepId, Date fechaCreacion) {
		this.tipId = tipId;
		this.tipDescripcion = tipDescripcion;
		this.tipEstado = tipEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public TipoProducto(int tipId, String tipDescripcion, char tipEstado, int uepId, Date fechaCreacion,
			Integer userModifica, Date fechaModifica, Set<Producto> productos) {
		this.tipId = tipId;
		this.tipDescripcion = tipDescripcion;
		this.tipEstado = tipEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
		this.productos = productos;
	}

	@Id
	@SequenceGenerator(name="TIPO_PRODUCTO_GENERATOR", sequenceName="SEQ_TIPO_PRODUCTO" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TIPO_PRODUCTO_GENERATOR" )
	@Column(name = "tip_id", unique = true, nullable = false)
	public int getTipId() {
		return this.tipId;
	}

	public void setTipId(int tipId) {
		this.tipId = tipId;
	}

	@Column(name = "tip_descripcion", nullable = false, length = 250)
	public String getTipDescripcion() {
		return this.tipDescripcion;
	}

	public void setTipDescripcion(String tipDescripcion) {
		this.tipDescripcion = tipDescripcion;
	}

	@Column(name = "tip_estado", nullable = false, length = 1)
	public char getTipEstado() {
		return this.tipEstado;
	}

	public void setTipEstado(char tipEstado) {
		this.tipEstado = tipEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoProducto")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
