package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "tipo_documento", schema = "sfe")
public class TipoDocumento implements java.io.Serializable {

	private int tidId;
	private String tidCodigo;
	private String tidDescripcion;
	private char tidEstado;
	private String tidAcronimo;

	public TipoDocumento() {
	}

	public TipoDocumento(int tidId, String tidCodigo, String tidDescripcion, char tidEstado) {
		this.tidId = tidId;
		this.tidCodigo = tidCodigo;
		this.tidDescripcion = tidDescripcion;
		this.tidEstado = tidEstado;
	}

	public TipoDocumento(int tidId, String tidCodigo, String tidDescripcion, char tidEstado, String tidAcronimo) {
		this.tidId = tidId;
		this.tidCodigo = tidCodigo;
		this.tidDescripcion = tidDescripcion;
		this.tidEstado = tidEstado;
		this.tidAcronimo = tidAcronimo;
	}

	@Id

	@Column(name = "tid_id", unique = true, nullable = false)
	public int getTidId() {
		return this.tidId;
	}

	public void setTidId(int tidId) {
		this.tidId = tidId;
	}

	@Column(name = "tid_codigo", nullable = false, length = 5)
	public String getTidCodigo() {
		return this.tidCodigo;
	}

	public void setTidCodigo(String tidCodigo) {
		this.tidCodigo = tidCodigo;
	}

	@Column(name = "tid_descripcion", nullable = false, length = 100)
	public String getTidDescripcion() {
		return this.tidDescripcion;
	}

	public void setTidDescripcion(String tidDescripcion) {
		this.tidDescripcion = tidDescripcion;
	}

	@Column(name = "tid_estado", nullable = false, length = 1)
	public char getTidEstado() {
		return this.tidEstado;
	}

	public void setTidEstado(char tidEstado) {
		this.tidEstado = tidEstado;
	}

	@Column(name = "tid_acronimo", length = 5)
	public String getTidAcronimo() {
		return this.tidAcronimo;
	}

	public void setTidAcronimo(String tidAcronimo) {
		this.tidAcronimo = tidAcronimo;
	}

}
