package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoCliente generated by hbm2java
 */
@Entity
@Table(name = "tipo_cliente", schema = "sfe")
public class TipoCliente implements java.io.Serializable {

	private int tpc;
	private char tpcDescripcion;
	private char tpcEstado;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;

	public TipoCliente() {
	}

	public TipoCliente(int tpc, char tpcDescripcion, char tpcEstado, int uepId, Date fechaCreacion) {
		this.tpc = tpc;
		this.tpcDescripcion = tpcDescripcion;
		this.tpcEstado = tpcEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
	}

	public TipoCliente(int tpc, char tpcDescripcion, char tpcEstado, int uepId, Date fechaCreacion,
			Integer userModifica, Date fechaModifica) {
		this.tpc = tpc;
		this.tpcDescripcion = tpcDescripcion;
		this.tpcEstado = tpcEstado;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
	}

	@Id

	@Column(name = "tpc", unique = true, nullable = false)
	public int getTpc() {
		return this.tpc;
	}

	public void setTpc(int tpc) {
		this.tpc = tpc;
	}

	@Column(name = "tpc_descripcion", nullable = false, length = 1)
	public char getTpcDescripcion() {
		return this.tpcDescripcion;
	}

	public void setTpcDescripcion(char tpcDescripcion) {
		this.tpcDescripcion = tpcDescripcion;
	}

	@Column(name = "tpc_estado", nullable = false, length = 1)
	public char getTpcEstado() {
		return this.tpcEstado;
	}

	public void setTpcEstado(char tpcEstado) {
		this.tpcEstado = tpcEstado;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
