package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usershasgroups generated by hbm2java
 */
@Entity
@Table(name = "usershasgroups", schema = "sfe")
public class Usershasgroups implements java.io.Serializable {

	private UsershasgroupsId id;

	public Usershasgroups() {
	}

	public Usershasgroups(UsershasgroupsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", length = 250)),
			@AttributeOverride(name = "groupname", column = @Column(name = "groupname", length = 250)) })
	public UsershasgroupsId getId() {
		return this.id;
	}

	public void setId(UsershasgroupsId id) {
		this.id = id;
	}

}
