package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "sfe")
public class Users implements java.io.Serializable {

	private String username;
	private String userpassword;

	public Users() {
	}

	public Users(String username, String userpassword) {
		this.username = username;
		this.userpassword = userpassword;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userpassword", nullable = false, length = 250)
	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

}
