package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioEmpresaPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_empresa_perfil", schema = "sfe")
public class UsuarioEmpresaPerfil implements java.io.Serializable {

	private int userCreacion;
	private int uepId;
	private int usuId;
	private int empId;
	private int perId;
	private char estado;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;

	public UsuarioEmpresaPerfil() {
	}

	public UsuarioEmpresaPerfil(int userCreacion, int uepId, int usuId, int empId, int perId, char estado,
			Date fechaCreacion) {
		this.userCreacion = userCreacion;
		this.uepId = uepId;
		this.usuId = usuId;
		this.empId = empId;
		this.perId = perId;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
	}

	public UsuarioEmpresaPerfil(int userCreacion, int uepId, int usuId, int empId, int perId, char estado,
			Date fechaCreacion, Integer userModifica, Date fechaModifica) {
		this.userCreacion = userCreacion;
		this.uepId = uepId;
		this.usuId = usuId;
		this.empId = empId;
		this.perId = perId;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
	}

	@Id

	@Column(name = "user_creacion", unique = true, nullable = false)
	public int getUserCreacion() {
		return this.userCreacion;
	}

	public void setUserCreacion(int userCreacion) {
		this.userCreacion = userCreacion;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Column(name = "usu_id", nullable = false)
	public int getUsuId() {
		return this.usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	@Column(name = "emp_id", nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "per_id", nullable = false)
	public int getPerId() {
		return this.perId;
	}

	public void setPerId(int perId) {
		this.perId = perId;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
