package model;
// Generated 12-jun-2018 19:07:14 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "sfe")
public class Usuario implements java.io.Serializable {

	private int usuId;
	private String usuNick;
	private String usuNombres;
	private String usuApellidos;
	private String usuTelefono;
	private String usuDireccion;
	private String usuEmail;
	private int uepId;
	private Date fechaCreacion;
	private Integer userModifica;
	private Date fechaModifica;
	private String usuPass;

	public Usuario() {
	}

	public Usuario(int usuId, String usuNick, String usuNombres, String usuApellidos, String usuEmail, int uepId,
			Date fechaCreacion, String usuPass) {
		this.usuId = usuId;
		this.usuNick = usuNick;
		this.usuNombres = usuNombres;
		this.usuApellidos = usuApellidos;
		this.usuEmail = usuEmail;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.usuPass = usuPass;
	}

	public Usuario(int usuId, String usuNick, String usuNombres, String usuApellidos, String usuTelefono,
			String usuDireccion, String usuEmail, int uepId, Date fechaCreacion, Integer userModifica,
			Date fechaModifica, String usuPass) {
		this.usuId = usuId;
		this.usuNick = usuNick;
		this.usuNombres = usuNombres;
		this.usuApellidos = usuApellidos;
		this.usuTelefono = usuTelefono;
		this.usuDireccion = usuDireccion;
		this.usuEmail = usuEmail;
		this.uepId = uepId;
		this.fechaCreacion = fechaCreacion;
		this.userModifica = userModifica;
		this.fechaModifica = fechaModifica;
		this.usuPass = usuPass;
	}

	@Id

	@Column(name = "usu_id", unique = true, nullable = false)
	public int getUsuId() {
		return this.usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	@Column(name = "usu_nick", nullable = false, length = 100)
	public String getUsuNick() {
		return this.usuNick;
	}

	public void setUsuNick(String usuNick) {
		this.usuNick = usuNick;
	}

	@Column(name = "usu_nombres", nullable = false, length = 250)
	public String getUsuNombres() {
		return this.usuNombres;
	}

	public void setUsuNombres(String usuNombres) {
		this.usuNombres = usuNombres;
	}

	@Column(name = "usu_apellidos", nullable = false, length = 250)
	public String getUsuApellidos() {
		return this.usuApellidos;
	}

	public void setUsuApellidos(String usuApellidos) {
		this.usuApellidos = usuApellidos;
	}

	@Column(name = "usu_telefono", length = 20)
	public String getUsuTelefono() {
		return this.usuTelefono;
	}

	public void setUsuTelefono(String usuTelefono) {
		this.usuTelefono = usuTelefono;
	}

	@Column(name = "usu_direccion", length = 100)
	public String getUsuDireccion() {
		return this.usuDireccion;
	}

	public void setUsuDireccion(String usuDireccion) {
		this.usuDireccion = usuDireccion;
	}

	@Column(name = "usu_email", nullable = false, length = 250)
	public String getUsuEmail() {
		return this.usuEmail;
	}

	public void setUsuEmail(String usuEmail) {
		this.usuEmail = usuEmail;
	}

	@Column(name = "uep_id", nullable = false)
	public int getUepId() {
		return this.uepId;
	}

	public void setUepId(int uepId) {
		this.uepId = uepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "user_modifica")
	public Integer getUserModifica() {
		return this.userModifica;
	}

	public void setUserModifica(Integer userModifica) {
		this.userModifica = userModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 29)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@Column(name = "usu_pass", nullable = false, length = 250)
	public String getUsuPass() {
		return this.usuPass;
	}

	public void setUsuPass(String usuPass) {
		this.usuPass = usuPass;
	}

}
